import { Link } from "react-router-dom";
import { APP_NAME, CONTACT_EMAIL } from "@/lib/constants";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-10">
      <h2 className="font-display text-xl font-bold text-ink sm:text-2xl">{title}</h2>
      <div className="mt-3 space-y-4 text-base leading-relaxed text-ink-muted text-pretty">
        {children}
      </div>
    </section>
  );
}

function SubTitle({ children }: { children: React.ReactNode }) {
  return <h3 className="font-semibold text-ink">{children}</h3>;
}

function Bullets({ items }: { items: React.ReactNode[] }) {
  return (
    <ul className="list-disc space-y-2 pl-5">
      {items.map((item, i) => (
        <li key={i}>{item}</li>
      ))}
    </ul>
  );
}

export default function Terms() {
  return (
    <div className="overflow-x-hidden bg-night">
      <div className="container-px pt-28 pb-20 sm:pt-36 sm:pb-28">
        <article className="mx-auto max-w-3xl">
          <header>
            <span className="eyebrow">Legal</span>
            <h1 className="mt-4 font-display text-4xl font-extrabold leading-tight text-ink text-balance sm:text-5xl">
              Terms of Service
            </h1>
            <p className="mt-3 text-sm font-medium text-ink-muted">
              Last updated: April 13, 2026
            </p>
          </header>

          <div className="mt-8 text-base leading-relaxed text-ink-muted text-pretty">
            <p>
              By using {APP_NAME} ("the app"), you agree to these terms. If you do
              not agree, do not use the app.
            </p>
          </div>

          <Section title="1. Service description">
            <p>
              {APP_NAME} is a fitness and nutrition tracking application designed for
              combat sport athletes and individuals managing their weight. The app
              provides tools for weight tracking, meal logging, sleep tracking,
              training session management, recovery analytics, and AI-generated
              nutritional guidance.
            </p>
          </Section>

          <Section title="2. Medical disclaimer">
            <p>
              <strong className="text-ink">
                {APP_NAME} is not a medical device and does not provide medical
                advice.
              </strong>{" "}
              All information, recommendations, and protocols generated by the app —
              including AI coaching, fight week plans, rehydration protocols, and
              diet analysis — are for educational and informational purposes only.
            </p>
            <Bullets
              items={[
                "Always consult a qualified physician, sports dietitian, or medical professional before starting any weight cut, dietary change, or rehydration protocol",
                "The app is not a substitute for professional medical advice, diagnosis, or treatment",
                "Stop any protocol and seek immediate medical attention if you experience dizziness, confusion, nausea, chest pain, or any adverse symptoms",
                "Weight cutting carries inherent health risks — the app helps plan and track, but you are responsible for your safety",
                "AI-generated advice is based on general sports science research and may not account for your specific medical conditions",
              ]}
            />
          </Section>

          <Section title="3. Account & eligibility">
            <Bullets
              items={[
                "You must be at least 17 years old to use the app",
                "You are responsible for maintaining the security of your account credentials",
                "You must provide accurate information when creating your account",
                "One account per person — sharing accounts is not permitted",
              ]}
            />
          </Section>

          <Section title="4. Acceptable use">
            <p>You agree not to:</p>
            <Bullets
              items={[
                "Use the app for any unlawful purpose",
                "Attempt to access other users' data or accounts",
                "Reverse-engineer, decompile, or extract source code from the app",
                "Abuse AI features (excessive requests, prompt injection, or automated scraping)",
                "Upload harmful, offensive, or illegal content",
                "Misrepresent the app's output as professional medical advice to others",
              ]}
            />
          </Section>

          <Section title="5. AI-generated content">
            <p>
              The app uses artificial intelligence (powered by Groq) to generate
              meal plans, diet analysis, coaching advice, and other content.
              AI-generated content:
            </p>
            <Bullets
              items={[
                "May contain inaccuracies — always verify nutritional data and recommendations",
                "Is generated from general knowledge and does not constitute professional advice",
                "Should not be relied upon as the sole basis for health or dietary decisions",
                "May vary between requests for the same input",
              ]}
            />
          </Section>

          <Section title="6. Subscriptions & in-app purchases">
            <SubTitle>Free tier</SubTitle>
            <p>
              The free tier includes weight tracking, nutrition logging, training
              session logging, and the daily-wisdom feature. AI-powered features
              (meal analysis, coach chat, weight insights, meal planning, etc.)
              require a Pro subscription.
            </p>

            <SubTitle>Pro subscription</SubTitle>
            <Bullets
              items={[
                "Pro unlocks unlimited AI features across the app",
                "Available as a monthly or annual subscription via Apple In-App Purchase",
                "Payment is charged to your Apple ID account at confirmation of purchase",
                "Subscription automatically renews unless cancelled at least 24 hours before the end of the current billing period",
                "You can manage or cancel your subscription in your Apple ID account settings or via the app's Settings > Manage Subscription",
              ]}
            />

            <SubTitle>Refunds</SubTitle>
            <p>
              All purchases are processed by Apple. Refund requests must be submitted
              through Apple's support channels. We do not process refunds directly.
            </p>

            <SubTitle>Price changes</SubTitle>
            <p>
              We may change subscription pricing. Any price change will take effect at
              the start of your next billing period after notice. You may cancel
              before the new price takes effect.
            </p>
          </Section>

          <Section title="7. Data & privacy">
            <p>
              Your use of the app is also governed by our{" "}
              <Link
                to="/privacy"
                className="font-semibold text-accent underline underline-offset-2 hover:text-brand-300"
              >
                Privacy Policy
              </Link>
              . By using the app, you consent to the collection and use of your data
              as described therein.
            </p>
          </Section>

          <Section title="8. Intellectual property">
            <p>
              The app, its design, code, branding, and content are the intellectual
              property of Pratik Rai. You may not reproduce, distribute, or create
              derivative works from any part of the app without written permission.
            </p>
          </Section>

          <Section title="9. Account termination">
            <Bullets
              items={[
                "You may delete your account at any time from Settings — this permanently removes all your data",
                "Deleting your account does not automatically cancel an active subscription — cancel via Apple ID settings first",
                "We reserve the right to suspend or terminate accounts that violate these terms",
                "Upon termination, all data associated with your account will be permanently deleted",
              ]}
            />
          </Section>

          <Section title="10. Limitation of liability">
            <p>
              To the maximum extent permitted by law, {APP_NAME} and its developers
              are not liable for any direct, indirect, incidental, or consequential
              damages arising from your use of the app. This includes but is not
              limited to:
            </p>
            <Bullets
              items={[
                "Health complications resulting from following app-generated protocols",
                "Data loss or service interruptions",
                "Inaccuracies in AI-generated content or nutritional data",
                "Third-party service outages (Convex, Groq, RevenueCat, etc.)",
              ]}
            />
          </Section>

          <Section title="11. Changes to terms">
            <p>
              We may update these terms from time to time. Changes take effect when
              posted on this page. Continued use of the app after changes constitutes
              acceptance of the updated terms.
            </p>
          </Section>

          <Section title="12. Governing law">
            <p>
              These terms are governed by the laws of England and Wales. Any disputes
              will be subject to the exclusive jurisdiction of the courts of England
              and Wales.
            </p>
          </Section>

          <Section title="13. Contact">
            <p>
              For questions about these terms, email us at{" "}
              <a
                href={`mailto:${CONTACT_EMAIL}`}
                className="font-semibold text-accent underline underline-offset-2 hover:text-brand-300"
              >
                {CONTACT_EMAIL}
              </a>
              .
            </p>
          </Section>

          <footer className="mt-12 border-t border-white/[0.07] pt-6 text-sm text-ink-muted">
            See also our{" "}
            <Link
              to="/privacy"
              className="font-semibold text-accent underline underline-offset-2 hover:text-brand-300"
            >
              Privacy Policy
            </Link>
            .
          </footer>
        </article>
      </div>
    </div>
  );
}
